# Generated by Django 5.1.6 on 2025-02-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CYON', '0005_donation_alter_outreach_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='reference',
            field=models.CharField(default='', max_length=200),
        ),
    ]
