# Generated by Django 5.1.5 on 2025-02-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CYON', '0005_alter_candidate_image_alter_program_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
