# Generated by Django 5.1.5 on 2025-02-17 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CYON', '0006_candidate_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-17 18:43:43'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
