# Generated by Django 5.1.5 on 2025-02-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CYON', '0007_alter_candidate_date_created_alter_vote_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
